linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - golint
    - ineffassign
    - unconvert
    - misspell
    - govet

    # TODO: Will enable and fix errors in subsequent merge request.
    # - gosimple
    # - staticcheck
    # - structcheck
    # - typecheck
    # - unused
    # - varcheck
    # - exportloopref
    # - forcetypeassert
    # - gocritic
    # - gosec
    # - revive
    # - promlinter
    # - tagliatelle
linters-settings:
  exhaustive:
    check-generated: false
  exhaustivestruct:
    check-generated: false
run:
  skip-files:
    - ".*\\.pb\\.go$"
