// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: thorchain/v1/x/thorchain/genesis.proto

package thorchain

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	gitlab_com_thorchain_thornode_x_thorchain_types "gitlab.com/thorchain/thornode/x/thorchain/types"
	types "gitlab.com/thorchain/thornode/x/thorchain/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	Pools               []types.Pool                                                        `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools"`
	LiquidityProviders  gitlab_com_thorchain_thornode_x_thorchain_types.LiquidityProviders  `protobuf:"bytes,2,rep,name=liquidity_providers,json=liquidityProviders,proto3,castrepeated=gitlab.com/thorchain/thornode/x/thorchain/types.LiquidityProviders" json:"liquidity_providers"`
	ObservedTxInVoters  gitlab_com_thorchain_thornode_x_thorchain_types.ObservedTxVoters    `protobuf:"bytes,3,rep,name=observed_tx_in_voters,json=observedTxInVoters,proto3,castrepeated=gitlab.com/thorchain/thornode/x/thorchain/types.ObservedTxVoters" json:"observed_tx_in_voters"`
	ObservedTxOutVoters gitlab_com_thorchain_thornode_x_thorchain_types.ObservedTxVoters    `protobuf:"bytes,4,rep,name=observed_tx_out_voters,json=observedTxOutVoters,proto3,castrepeated=gitlab.com/thorchain/thornode/x/thorchain/types.ObservedTxVoters" json:"observed_tx_out_voters"`
	TxOuts              []types.TxOut                                                       `protobuf:"bytes,5,rep,name=tx_outs,json=txOuts,proto3" json:"tx_outs"`
	NodeAccounts        gitlab_com_thorchain_thornode_x_thorchain_types.NodeAccounts        `protobuf:"bytes,6,rep,name=node_accounts,json=nodeAccounts,proto3,castrepeated=gitlab.com/thorchain/thornode/x/thorchain/types.NodeAccounts" json:"node_accounts"`
	Vaults              gitlab_com_thorchain_thornode_x_thorchain_types.Vaults              `protobuf:"bytes,7,rep,name=vaults,proto3,castrepeated=gitlab.com/thorchain/thornode/x/thorchain/types.Vaults" json:"vaults"`
	Reserve             uint64                                                              `protobuf:"varint,8,opt,name=reserve,proto3" json:"reserve,omitempty"`
	LastSignedHeight    int64                                                               `protobuf:"varint,10,opt,name=last_signed_height,json=lastSignedHeight,proto3" json:"last_signed_height,omitempty"`
	LastChainHeights    map[string]int64                                                    `protobuf:"bytes,11,rep,name=last_chain_heights,json=lastChainHeights,proto3" json:"last_chain_heights,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	ReserveContributors gitlab_com_thorchain_thornode_x_thorchain_types.ReserveContributors `protobuf:"bytes,12,rep,name=reserve_contributors,json=reserveContributors,proto3,castrepeated=gitlab.com/thorchain/thornode/x/thorchain/types.ReserveContributors" json:"reserve_contributors"`
	Network             types.Network                                                       `protobuf:"bytes,13,opt,name=network,proto3" json:"network"`
	MsgSwaps            []types.MsgSwap                                                     `protobuf:"bytes,19,rep,name=msg_swaps,json=msgSwaps,proto3" json:"msg_swaps"`
	NetworkFees         []types.NetworkFee                                                  `protobuf:"bytes,20,rep,name=network_fees,json=networkFees,proto3" json:"network_fees"`
	ChainContracts      []types.ChainContract                                               `protobuf:"bytes,22,rep,name=chain_contracts,json=chainContracts,proto3" json:"chain_contracts"`
	THORNames           []types.THORName                                                    `protobuf:"bytes,23,rep,name=THORNames,proto3" json:"THORNames"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b10f0e2a2ac9ce40, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetPools() []types.Pool {
	if m != nil {
		return m.Pools
	}
	return nil
}

func (m *GenesisState) GetLiquidityProviders() gitlab_com_thorchain_thornode_x_thorchain_types.LiquidityProviders {
	if m != nil {
		return m.LiquidityProviders
	}
	return nil
}

func (m *GenesisState) GetObservedTxInVoters() gitlab_com_thorchain_thornode_x_thorchain_types.ObservedTxVoters {
	if m != nil {
		return m.ObservedTxInVoters
	}
	return nil
}

func (m *GenesisState) GetObservedTxOutVoters() gitlab_com_thorchain_thornode_x_thorchain_types.ObservedTxVoters {
	if m != nil {
		return m.ObservedTxOutVoters
	}
	return nil
}

func (m *GenesisState) GetTxOuts() []types.TxOut {
	if m != nil {
		return m.TxOuts
	}
	return nil
}

func (m *GenesisState) GetNodeAccounts() gitlab_com_thorchain_thornode_x_thorchain_types.NodeAccounts {
	if m != nil {
		return m.NodeAccounts
	}
	return nil
}

func (m *GenesisState) GetVaults() gitlab_com_thorchain_thornode_x_thorchain_types.Vaults {
	if m != nil {
		return m.Vaults
	}
	return nil
}

func (m *GenesisState) GetReserve() uint64 {
	if m != nil {
		return m.Reserve
	}
	return 0
}

func (m *GenesisState) GetLastSignedHeight() int64 {
	if m != nil {
		return m.LastSignedHeight
	}
	return 0
}

func (m *GenesisState) GetLastChainHeights() map[string]int64 {
	if m != nil {
		return m.LastChainHeights
	}
	return nil
}

func (m *GenesisState) GetReserveContributors() gitlab_com_thorchain_thornode_x_thorchain_types.ReserveContributors {
	if m != nil {
		return m.ReserveContributors
	}
	return nil
}

func (m *GenesisState) GetNetwork() types.Network {
	if m != nil {
		return m.Network
	}
	return types.Network{}
}

func (m *GenesisState) GetMsgSwaps() []types.MsgSwap {
	if m != nil {
		return m.MsgSwaps
	}
	return nil
}

func (m *GenesisState) GetNetworkFees() []types.NetworkFee {
	if m != nil {
		return m.NetworkFees
	}
	return nil
}

func (m *GenesisState) GetChainContracts() []types.ChainContract {
	if m != nil {
		return m.ChainContracts
	}
	return nil
}

func (m *GenesisState) GetTHORNames() []types.THORName {
	if m != nil {
		return m.THORNames
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "thorchain.GenesisState")
	proto.RegisterMapType((map[string]int64)(nil), "thorchain.GenesisState.LastChainHeightsEntry")
}

func init() {
	proto.RegisterFile("thorchain/v1/x/thorchain/genesis.proto", fileDescriptor_b10f0e2a2ac9ce40)
}

var fileDescriptor_b10f0e2a2ac9ce40 = []byte{
	// 832 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x95, 0x4d, 0x6f, 0xe3, 0x44,
	0x18, 0xc7, 0xe3, 0xc6, 0x4d, 0x9c, 0x49, 0xb6, 0x71, 0x27, 0x69, 0x18, 0x7a, 0xc8, 0x46, 0x1c,
	0x20, 0x08, 0xd6, 0xa1, 0x5d, 0xb1, 0x5a, 0xad, 0x16, 0x04, 0x0e, 0x2f, 0xc5, 0x2c, 0xdb, 0x95,
	0xbb, 0xea, 0x01, 0x0e, 0x96, 0x13, 0x0f, 0x8e, 0x55, 0xc7, 0x13, 0x3c, 0xe3, 0x34, 0x39, 0xf0,
	0x1d, 0x90, 0x10, 0x07, 0xbe, 0x02, 0x9f, 0xa4, 0xc7, 0x1e, 0x7b, 0x02, 0xd4, 0x7e, 0x11, 0xe4,
	0x99, 0x71, 0xe3, 0x92, 0x22, 0x9c, 0xcb, 0x5e, 0x2c, 0xcf, 0x7f, 0x9e, 0xdf, 0x33, 0xff, 0x79,
	0xe6, 0x0d, 0xbc, 0xcb, 0x26, 0x24, 0x1e, 0x4f, 0xdc, 0x20, 0x1a, 0xcc, 0x0f, 0x06, 0x8b, 0xc1,
	0xaa, 0xe9, 0xe3, 0x08, 0xd3, 0x80, 0x1a, 0xb3, 0x98, 0x30, 0x02, 0x6b, 0xb7, 0x1d, 0xfb, 0xc6,
	0x7f, 0x22, 0x6c, 0x39, 0xc3, 0x94, 0x7f, 0x9d, 0x19, 0x21, 0xa1, 0x40, 0xf7, 0x9f, 0x16, 0x89,
	0xe7, 0x82, 0x33, 0x26, 0x11, 0x8b, 0xdd, 0x31, 0x93, 0xe4, 0xc7, 0x45, 0xc8, 0x08, 0xb3, 0x73,
	0x12, 0x9f, 0x39, 0x3f, 0x62, 0x2c, 0xb1, 0x47, 0xff, 0x83, 0x4d, 0xa9, 0xef, 0xd0, 0x73, 0x77,
	0x26, 0xc3, 0x0f, 0x36, 0x18, 0x45, 0x22, 0x9f, 0x14, 0x41, 0x62, 0x4c, 0x71, 0x3c, 0xc7, 0x62,
	0x52, 0xc1, 0x28, 0x61, 0x24, 0x96, 0xf8, 0xa0, 0x08, 0x3e, 0x77, 0x93, 0x30, 0x2b, 0xc4, 0x47,
	0x45, 0x00, 0xb6, 0x70, 0x48, 0x92, 0x11, 0x4f, 0x0a, 0x4d, 0x8a, 0x78, 0xd8, 0x71, 0xc7, 0x63,
	0x92, 0x44, 0x1b, 0x95, 0x9c, 0x8c, 0xf8, 0xcc, 0x3c, 0x87, 0x2d, 0x24, 0xf6, 0xbc, 0x08, 0x16,
	0x06, 0x3f, 0x25, 0x81, 0x17, 0xb0, 0xa5, 0x33, 0x8b, 0xc9, 0x3c, 0xf0, 0x70, 0x56, 0x8f, 0xc3,
	0x42, 0xd3, 0x9b, 0x90, 0x38, 0x72, 0xa7, 0xd9, 0x22, 0xb7, 0x7d, 0xe2, 0x13, 0xfe, 0x3b, 0x48,
	0xff, 0x84, 0xfa, 0xce, 0x55, 0x1d, 0x34, 0xbe, 0x16, 0x1b, 0xf7, 0x84, 0xb9, 0x0c, 0xc3, 0xf7,
	0xc0, 0x76, 0xba, 0x15, 0x29, 0x52, 0x7a, 0xe5, 0x7e, 0xfd, 0xb0, 0x6e, 0xf0, 0x8c, 0xc6, 0x2b,
	0x42, 0x42, 0x53, 0xbd, 0xf8, 0xf3, 0x61, 0xc9, 0x16, 0xfd, 0xf0, 0x37, 0x05, 0xb4, 0xd6, 0x0d,
	0x52, 0xb4, 0xc5, 0x39, 0x24, 0xb9, 0x17, 0x59, 0xc4, 0x2b, 0x19, 0x60, 0x5a, 0x69, 0x92, 0x3f,
	0xfe, 0x7a, 0x68, 0xfa, 0x01, 0x0b, 0xdd, 0x91, 0x31, 0x26, 0xd3, 0xbc, 0xff, 0xd4, 0x34, 0xf1,
	0xf0, 0xfa, 0xa4, 0xd6, 0x53, 0x51, 0x1b, 0x86, 0x6b, 0x1a, 0xfc, 0x55, 0x01, 0x7b, 0xb9, 0x7a,
	0x3b, 0x41, 0xe4, 0xcc, 0x09, 0x4b, 0x9d, 0x95, 0xb9, 0xb3, 0x8e, 0x74, 0x76, 0x2c, 0x63, 0x5e,
	0x2f, 0x4e, 0xd3, 0x6e, 0xf3, 0x48, 0xfa, 0xfa, 0x6c, 0x53, 0x5f, 0xff, 0x4a, 0x44, 0x6d, 0x48,
	0x6e, 0x95, 0x6f, 0x22, 0xa1, 0xa5, 0xd5, 0xea, 0xe4, 0x5d, 0x91, 0x84, 0x65, 0xb6, 0xd4, 0x37,
	0x64, 0xab, 0xb5, 0xb2, 0x75, 0x9c, 0x30, 0xe9, 0xeb, 0x03, 0x50, 0x15, 0x6e, 0x28, 0xda, 0xe6,
	0x3e, 0x1a, 0xd2, 0x07, 0x0f, 0x92, 0x2b, 0x5e, 0x61, 0x69, 0x83, 0xc2, 0x9f, 0xc1, 0x83, 0xfc,
	0x09, 0xa0, 0xa8, 0xc2, 0x11, 0x28, 0x91, 0x97, 0xc4, 0xc3, 0x9f, 0x8b, 0x2e, 0xf3, 0x0b, 0x69,
	0xfb, 0xf9, 0xa6, 0xb6, 0x73, 0x49, 0xa8, 0xdd, 0x88, 0x72, 0x2d, 0xe8, 0x81, 0x0a, 0x3f, 0xe3,
	0x14, 0x55, 0xef, 0x58, 0x3d, 0x4d, 0x45, 0xf3, 0x53, 0x39, 0xe2, 0x93, 0x4d, 0x47, 0xe4, 0x38,
	0xb5, 0x65, 0x6e, 0x88, 0x40, 0x55, 0x5e, 0x44, 0x48, 0xeb, 0x29, 0x7d, 0xd5, 0xce, 0x9a, 0xf0,
	0x43, 0x00, 0x43, 0x97, 0x32, 0x87, 0x06, 0x7e, 0x84, 0x3d, 0x67, 0x82, 0x03, 0x7f, 0xc2, 0x10,
	0xe8, 0x29, 0xfd, 0xb2, 0xad, 0xa7, 0x3d, 0x27, 0xbc, 0xe3, 0x88, 0xeb, 0xf0, 0x07, 0x19, 0x2d,
	0x2e, 0x6a, 0x11, 0x4c, 0x51, 0x9d, 0x3b, 0x7f, 0xb4, 0x7a, 0x12, 0x8c, 0xfc, 0xe9, 0x33, 0x5e,
	0xb8, 0x94, 0x0d, 0x53, 0x59, 0x24, 0xa1, 0x5f, 0x46, 0x2c, 0x5e, 0x8a, 0xe4, 0x79, 0x19, 0xfe,
	0xae, 0x80, 0xf6, 0x3d, 0xd7, 0x25, 0x45, 0x0d, 0x9e, 0xff, 0x6d, 0x59, 0x19, 0x5b, 0x84, 0x0c,
	0x57, 0x11, 0xe6, 0xb7, 0xb2, 0x4c, 0xc3, 0x4d, 0xcb, 0xb4, 0x9e, 0x8b, 0xda, 0xad, 0x78, 0x5d,
	0x84, 0x06, 0xa8, 0xca, 0xcb, 0x1f, 0x3d, 0xe8, 0x29, 0xfd, 0xfa, 0xe1, 0x4e, 0xb6, 0x3f, 0x84,
	0x2a, 0x37, 0x55, 0x16, 0x04, 0x0f, 0x40, 0x2d, 0x7b, 0x60, 0x28, 0x6a, 0x71, 0xff, 0x19, 0xf1,
	0x1d, 0xf5, 0x4f, 0xce, 0xdd, 0x99, 0x24, 0xb4, 0xa9, 0x68, 0x52, 0xf8, 0x0c, 0x34, 0x72, 0xaf,
	0x18, 0x45, 0x6d, 0x4e, 0xed, 0xde, 0x1d, 0xe7, 0x2b, 0x8c, 0x25, 0x58, 0x8f, 0x6e, 0x15, 0x0a,
	0x87, 0xa0, 0x79, 0xf7, 0xed, 0xa4, 0xa8, 0xc3, 0xf1, 0xb6, 0xc4, 0x79, 0xa1, 0x87, 0xb2, 0x53,
	0x66, 0xd8, 0x19, 0xe7, 0x45, 0x0a, 0x1f, 0x83, 0xda, 0xeb, 0xa3, 0x63, 0xfb, 0xa5, 0x3b, 0xc5,
	0x14, 0xbd, 0xc5, 0xf1, 0x66, 0x76, 0x70, 0xa4, 0x2e, 0xc9, 0x55, 0xdc, 0xfe, 0x10, 0xec, 0xdd,
	0xbb, 0xbe, 0x50, 0x07, 0xe5, 0x33, 0xbc, 0x44, 0x4a, 0x4f, 0xe9, 0xd7, 0xec, 0xf4, 0x17, 0xb6,
	0xc1, 0xf6, 0xdc, 0x0d, 0x13, 0x8c, 0xb6, 0xf8, 0xee, 0x12, 0x8d, 0x67, 0x5b, 0x4f, 0x15, 0x4b,
	0xd5, 0x6a, 0x3a, 0xb0, 0x54, 0x6d, 0x47, 0x6f, 0x5a, 0xaa, 0xd6, 0xd4, 0x75, 0x4b, 0xd5, 0x74,
	0x7d, 0xd7, 0x52, 0xb5, 0x5d, 0x1d, 0x5a, 0xaa, 0x06, 0xf5, 0x96, 0xa5, 0x6a, 0x7b, 0x7a, 0xc7,
	0x1c, 0x5e, 0x5c, 0x77, 0x95, 0xcb, 0xeb, 0xae, 0xf2, 0xf7, 0x75, 0x57, 0xf9, 0xe5, 0xa6, 0x5b,
	0xba, 0xbc, 0xe9, 0x96, 0xae, 0x6e, 0xba, 0xa5, 0xef, 0xdf, 0x2f, 0xbc, 0xf6, 0xa3, 0x0a, 0x7f,
	0x26, 0x1e, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0xb2, 0xb0, 0x93, 0x36, 0xf7, 0x08, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.THORNames) > 0 {
		for iNdEx := len(m.THORNames) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.THORNames[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xba
		}
	}
	if len(m.ChainContracts) > 0 {
		for iNdEx := len(m.ChainContracts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ChainContracts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xb2
		}
	}
	if len(m.NetworkFees) > 0 {
		for iNdEx := len(m.NetworkFees) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NetworkFees[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xa2
		}
	}
	if len(m.MsgSwaps) > 0 {
		for iNdEx := len(m.MsgSwaps) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MsgSwaps[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x9a
		}
	}
	{
		size, err := m.Network.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	if len(m.ReserveContributors) > 0 {
		for iNdEx := len(m.ReserveContributors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ReserveContributors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.LastChainHeights) > 0 {
		for k := range m.LastChainHeights {
			v := m.LastChainHeights[k]
			baseI := i
			i = encodeVarintGenesis(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintGenesis(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintGenesis(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x5a
		}
	}
	if m.LastSignedHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LastSignedHeight))
		i--
		dAtA[i] = 0x50
	}
	if m.Reserve != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Reserve))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Vaults) > 0 {
		for iNdEx := len(m.Vaults) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Vaults[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.NodeAccounts) > 0 {
		for iNdEx := len(m.NodeAccounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NodeAccounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.TxOuts) > 0 {
		for iNdEx := len(m.TxOuts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TxOuts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.ObservedTxOutVoters) > 0 {
		for iNdEx := len(m.ObservedTxOutVoters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ObservedTxOutVoters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.ObservedTxInVoters) > 0 {
		for iNdEx := len(m.ObservedTxInVoters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ObservedTxInVoters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.LiquidityProviders) > 0 {
		for iNdEx := len(m.LiquidityProviders) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LiquidityProviders[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Pools) > 0 {
		for iNdEx := len(m.Pools) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pools[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Pools) > 0 {
		for _, e := range m.Pools {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.LiquidityProviders) > 0 {
		for _, e := range m.LiquidityProviders {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ObservedTxInVoters) > 0 {
		for _, e := range m.ObservedTxInVoters {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ObservedTxOutVoters) > 0 {
		for _, e := range m.ObservedTxOutVoters {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.TxOuts) > 0 {
		for _, e := range m.TxOuts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.NodeAccounts) > 0 {
		for _, e := range m.NodeAccounts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Vaults) > 0 {
		for _, e := range m.Vaults {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.Reserve != 0 {
		n += 1 + sovGenesis(uint64(m.Reserve))
	}
	if m.LastSignedHeight != 0 {
		n += 1 + sovGenesis(uint64(m.LastSignedHeight))
	}
	if len(m.LastChainHeights) > 0 {
		for k, v := range m.LastChainHeights {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovGenesis(uint64(len(k))) + 1 + sovGenesis(uint64(v))
			n += mapEntrySize + 1 + sovGenesis(uint64(mapEntrySize))
		}
	}
	if len(m.ReserveContributors) > 0 {
		for _, e := range m.ReserveContributors {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.Network.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.MsgSwaps) > 0 {
		for _, e := range m.MsgSwaps {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.NetworkFees) > 0 {
		for _, e := range m.NetworkFees {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ChainContracts) > 0 {
		for _, e := range m.ChainContracts {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.THORNames) > 0 {
		for _, e := range m.THORNames {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pools", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pools = append(m.Pools, types.Pool{})
			if err := m.Pools[len(m.Pools)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidityProviders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidityProviders = append(m.LiquidityProviders, types.LiquidityProvider{})
			if err := m.LiquidityProviders[len(m.LiquidityProviders)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservedTxInVoters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ObservedTxInVoters = append(m.ObservedTxInVoters, types.ObservedTxVoter{})
			if err := m.ObservedTxInVoters[len(m.ObservedTxInVoters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservedTxOutVoters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ObservedTxOutVoters = append(m.ObservedTxOutVoters, types.ObservedTxVoter{})
			if err := m.ObservedTxOutVoters[len(m.ObservedTxOutVoters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxOuts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxOuts = append(m.TxOuts, types.TxOut{})
			if err := m.TxOuts[len(m.TxOuts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeAccounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeAccounts = append(m.NodeAccounts, types.NodeAccount{})
			if err := m.NodeAccounts[len(m.NodeAccounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vaults", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vaults = append(m.Vaults, types.Vault{})
			if err := m.Vaults[len(m.Vaults)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reserve", wireType)
			}
			m.Reserve = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reserve |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastSignedHeight", wireType)
			}
			m.LastSignedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastSignedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastChainHeights", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastChainHeights == nil {
				m.LastChainHeights = make(map[string]int64)
			}
			var mapkey string
			var mapvalue int64
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenesis
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenesis
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthGenesis
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthGenesis
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenesis
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipGenesis(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthGenesis
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.LastChainHeights[mapkey] = mapvalue
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveContributors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReserveContributors = append(m.ReserveContributors, types.ReserveContributor{})
			if err := m.ReserveContributors[len(m.ReserveContributors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Network", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Network.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgSwaps", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgSwaps = append(m.MsgSwaps, types.MsgSwap{})
			if err := m.MsgSwaps[len(m.MsgSwaps)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkFees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkFees = append(m.NetworkFees, types.NetworkFee{})
			if err := m.NetworkFees[len(m.NetworkFees)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 22:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainContracts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainContracts = append(m.ChainContracts, types.ChainContract{})
			if err := m.ChainContracts[len(m.ChainContracts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field THORNames", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.THORNames = append(m.THORNames, types.THORName{})
			if err := m.THORNames[len(m.THORNames)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
