FORMAT: 1A
HOST: http://localhost:1317

# THORChain API
This documentation outlines the API for THORChain.

NOTE: This document is a **work in progress**.

# Group Health Check

## Ping [GET /thorchain/ping]

+ Response 200 (plain/text)
    + Attributes 
        + ping: "pong" (string)
    
    + Body
            {"ping":"pong"}

# Group Pools
This section documents the pools API resources.

## Pool [/thorchain/pool/{ticker}]

A pool contains all the information of THORChain liquidity pool

+ Parameters
    + ticker: `BNB.BNB` (required, string) - The ticker of the pool

+ Attributes
    + balance_rune (string) -  Amount of rune the pool has
    + balance_asset (string) - Amount of asset the pool has
    + ticker (string) -  the ticker of the non-rune asset
    + pool_units (string) -  total number of units within the pool
    + status (string) -  the status of the pool

### Get a pool [GET]
Retrieve a liquidity pool with the given ticker

+ Response 200 (application/json)
    + Attribute (Pool)
    
### Get all the liquidity pools [GET /thorchain/pools]
Retrieve all the liquidity pools from THORChain

+ Response 200 (application/json)
    + Attributes (array[Pool])

## LiquidityProvider [/thorchain/pool/{ticker}/liquidity_providers]

+ Parameters
    + ticker: "BNB.BNB" (required, string) - The ticker of the pool

+ Attributes (object)
    + asset (string) -  the asset of the non-rune asset
    + rune_address (string) - the rune address of the liquidity provider
    + asset_address (string) - the non-rune asset address of the liquidity provider
    + last_add (string) - block height of the last add
    + last_withdraw (string) - block height of the last withdraw
    + units (string) - the total number of units of the pool
    + pending_rune (string) - rune that has been provided, but not committed yet. Awaiting a provision of the non-rune asset

### Get all liquidity providers of a pool [GET]

+ Response 200 (application/json)
    + Attributes (array[LiquidityProvider])

# Group Tx
This section document Tx API resource
## Tx [/thorchain/tx/{hash}]

+ Parameters
    + hash: `E17A0906E015F0C343691C18E475C8CB5F3F6C63F5BCDE0F3A341909763CC92B` (required, string) - Tx hash of an inbound transaction or outbound transaction
+ Attributes
    + tx (ObservedTx) -  observed tx information
    + status (enum) 
        + done
        + incomplete
    + out_hashes (array[string]) - a list of outbound hashes
    + block_height (string) - the block hight this tx get observed
    + signers (array[string]) - a list of signer address that has sign this tx off
    + observed_pub_key (string) - public key of the vault which observe this tx
      
### Get a tx with given hash [GET]
Retrieve a tx with the given hash from THORChain

+ Response 200 (application/json)
    + Body
    
            {
                "tx": {
                    "id": "CF524818D42B63D25BBA0CCC4909F127CAA645C0F9CD07324F2824CC151A64C7",
                    "chain": "BTC",
                    "from_address": "bcrt1q0s4mg25tu6termrk8egltfyme4q7sg3h8kkydt",
                    "to_address": "bcrt1qf3s7q037eancht7sg0aj995dht25rwrnqsf45e",
                    "coins": [
                    {
                        "asset": "BTC.BTC",
                        "amount": "150000000"
                    }],
                    "gas": [
                    {
                        "asset": "BTC.BTC",
                        "amount": "100000"
                    }],
                "memo": "ADD:BTC.BTC:tthor1zupk5lmc84r2dh738a9g3zscavannjy3nzplwt"
            },
            "status": "incomplete",
            "out_hashes": null,
            "block_height": "162",
            "signers": [
                "tthor1f3s7q037eancht7sg0aj995dht25rwrnu4ats5"
            ],
            "observed_pub_key": "tthorpub1addwnpepq27ck6u44zl8qqdnmzjjc8rg72amrxrsp42p9vd7kt6marhy6ww76z8shwe"
            }

## Get tx signers [/thorchain/tx/{hash}/signers]

+ Parameters
    + hash: "E17A0906E015F0C343691C18E475C8CB5F3F6C63F5BCDE0F3A341909763CC92B" (required, string) - Tx hash of an inbound transaction or outbound transaction

+ Attributes 
    + tx_id (string) - tx hash
    + tx (ObservedTx) - observed tx , the tx that reach 2/3 majority consensus
    + height (string) - block height that this tx reach super majority consensus
    + in_tx (array[ObservedTx]) - all observed tx
    + action - potential outbound tx
    + out_txs (array[string]) - outbound tx hashes

### Get tx signers [GET]
Get tx signers that match the request hash

+ Response 200 (application/json)
    + Body

            {
                "tx_id": "CF524818D42B63D25BBA0CCC4909F127CAA645C0F9CD07324F2824CC151A64C7",
                "tx": {
                    "tx": {
                    "id": "CF524818D42B63D25BBA0CCC4909F127CAA645C0F9CD07324F2824CC151A64C7",
                    "chain": "BTC",
                    "from_address": "bcrt1q0s4mg25tu6termrk8egltfyme4q7sg3h8kkydt",
                    "to_address": "bcrt1qf3s7q037eancht7sg0aj995dht25rwrnqsf45e",
                    "coins": [
                    {
                        "asset": "BTC.BTC",
                        "amount": "150000000"
                    }
                    ],
                    "gas": [
                    {
                        "asset": "BTC.BTC",
                        "amount": "100000"
                    }
                ],
                "memo": "ADD:BTC.BTC:tthor1zupk5lmc84r2dh738a9g3zscavannjy3nzplwt"
                },
                "status": "incomplete",
                "out_hashes": null,
                "block_height": "162",
                "signers": [
                    "tthor1f3s7q037eancht7sg0aj995dht25rwrnu4ats5"
                ],
                "observed_pub_key": "tthorpub1addwnpepq27ck6u44zl8qqdnmzjjc8rg72amrxrsp42p9vd7kt6marhy6ww76z8shwe"
                },
                "height": "15",
                "in_tx": [
                    {
                    "tx": {
                        "id": "CF524818D42B63D25BBA0CCC4909F127CAA645C0F9CD07324F2824CC151A64C7",
                        "chain": "BTC",
                        "from_address": "bcrt1q0s4mg25tu6termrk8egltfyme4q7sg3h8kkydt",
                        "to_address": "bcrt1qf3s7q037eancht7sg0aj995dht25rwrnqsf45e",
                        "coins": [
                        {
                            "asset": "BTC.BTC",
                            "amount": "150000000"
                        }
                        ],
                        "gas": [
                        {
                            "asset": "BTC.BTC",
                            "amount": "100000"
                        }
                        ],
                        "memo": "ADD:BTC.BTC:tthor1zupk5lmc84r2dh738a9g3zscavannjy3nzplwt"
                    },
                    "status": "incomplete",
                    "out_hashes": null,
                    "block_height": "162",
                    "signers": [
                        "tthor1f3s7q037eancht7sg0aj995dht25rwrnu4ats5"
                    ],
                    "observed_pub_key": "tthorpub1addwnpepq27ck6u44zl8qqdnmzjjc8rg72amrxrsp42p9vd7kt6marhy6ww76z8shwe"
                    }
                ],
                "actions": null,
                "out_txs": null
            }
# Group nodes

This section document all the API for Node resource
## Node [/thorchain/node/{node_address}]
+ Parameters
    + node_address: "tthor1f3s7q037eancht7sg0aj995dht25rwrnu4ats5" (string,required) - node address
+ Attributes
    + 
### Get a node [GET]    

# Group vaults

# Group others

# Data Structures

## Coin (object)
+ asset (string) - asset
+ amount (string) = amount
## ObservedTx (object)
+ id (string) - transaction hash
+ chain (string) - chain
+ from_address (string) - from address
+ to_address (string) - to address
+ coins (array[Coin]) - coins
+ gas  (array[Coin]) - amount of gas paid by the tx
+ memo (string) - memo