FORMAT: 1A

# THORChain API
This documentation outlines the API for THORChain.

 Add `?height={blockheight}` to the end of a query to return data for a specific block height (only works from current height to hardfork height). 

NOTE: This document is a **work in progress**.

# Group Health Check

## Ping [GET /thorchain/ping]

+ Response 200 (plain/text)
    + Attributes
        + ping: "pong" (string)
    + Body

                {"ping":"pong"}

# Group Pools
This section documents the pools API resources.

## Pool [/thorchain/pool/{asset}]
A pool contains all the information of THORChain liquidity pool

+ Parameters
    + asset: `BNB.BNB` (required, string) - The asset of the pool

+ Attributes
    + balance_rune (string) -  amount of rune the pool has
    + balance_asset (string) - amount of asset the pool has
    + asset (string) -  pool asset
    + pool_units (string) -  total number of units within the pool
    + status (string) -  status of the pool
    + synth_units (string) -  total number of synth units within the pool
    + pending_inbound_rune (string) -  amount of pending rune within the pool
    + pending_inbound_asset (string) -  amount of pending asset within the pool

### Get a pool [GET]
Retrieve a liquidity pool with the given asset

+ Response 200 (application/json)
    + Attributes (Pool)
    + Body

        {
          "balance_rune": "13460619152985",
          "balance_asset": "3197744873",
          "asset": "BTC.BTC",
          "pool_units": "14694928607473",
          "status": "Available",
          "synth_units": "0",
          "pending_inbound_rune": "464993836",
          "pending_inbound_asset": "101713319"
        }

### Get all the liquidity pools [GET /thorchain/pools]
Retrieve all the liquidity pools from THORChain

+ Response 200 (application/json)
    + Attributes (array[Pool])
    + Body

        [
          {
            "balance_rune": "990304018943",
            "balance_asset": "14902274220",
            "asset": "BCH.BCH",
            "pool_units": "944477442283",
            "status": "Available",
            "synth_units": "0",
            "pending_inbound_rune": "0",
            "pending_inbound_asset": "257058484"
          },
          {
            "balance_rune": "5227668587847",
            "balance_asset": "117072844569",
            "asset": "BNB.BNB",
            "pool_units": "4919785756191",
            "status": "Available",
            "synth_units": "0",
            "pending_inbound_rune": "0",
            "pending_inbound_asset": "1589030575"
          },
          {
            "balance_rune": "2906260051490",
            "balance_asset": "643467346",
            "asset": "BNB.BTCB-1DE",
            "pool_units": "2816600000000",
            "status": "Available",
            "synth_units": "0",
            "pending_inbound_rune": "0",
            "pending_inbound_asset": "230000"
          },
          {
            "balance_rune": "2414614240711",
            "balance_asset": "26650266002988",
            "asset": "BNB.BUSD-BD1",
            "pool_units": "2348364113912",
            "status": "Available",
            "synth_units": "0",
            "pending_inbound_rune": "0",
            "pending_inbound_asset": "82718240853"
          },
          {
            "balance_rune": "9019619987525",
            "balance_asset": "45893334588",
            "asset": "ETH.ETH",
            "pool_units": "8549256862314",
            "status": "Available",
            "synth_units": "0",
            "pending_inbound_rune": "14500000000",
            "pending_inbound_asset": "64193305"
          },
          {
            "balance_rune": "90000000000",
            "balance_asset": "33000000000",
            "asset": "ETH.LINK-0X514910771AF9CA656AF840DFF83E8264ECF986CA",
            "pool_units": "101000000000",
            "status": "Staged",
            "synth_units": "0",
            "pending_inbound_rune": "0",
            "pending_inbound_asset": "0"
          },
            {
            "balance_rune": "1028041431770",
            "balance_asset": "52175862117",
            "asset": "LTC.LTC",
            "pool_units": "1076474234756",
            "status": "Available",
            "synth_units": "0",
            "pending_inbound_rune": "6313867419",
            "pending_inbound_asset": "3910921839"
          }
        ]

### Get a liquidity provider of a pool [GET /thorchain/pool/{asset}/liquidity_provider/{address}]

+ Parameters
    + asset: `BNB.BNB` (required, string) - The asset of the pool
    + address: `thorxxxxxxxxxxxxxxxxxxxxxxx` (required, string) - The address of the liquidity provider

+ Response 200 (application/json)
    + Attributes (LiquidityProvider)
    + Body

          {
            "asset": "BNB.BNB",
            "rune_address": "thor1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "asset_address": "bnb1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "last_add_height": 82745,
            "units": "0",
            "pending_rune": "0",
            "pending_asset": "242000000",
            "pending_tx_Id": "C4C876802xxxxxxxxxxBC408829878446A37011EBBA0C5CAA3DD64A548879CB228",
            "rune_deposit_value": "0",
            "asset_deposit_value": "0"
          }

### Get all liquidity providers of a pool [GET /thorchain/pool/{asset}/liquidity_providers]

+ Parameters
    + asset: `BNB.BNB` (required, string) - The asset of the pool

+ Response 200 (application/json)
    + Attributes (array[LiquidityProvider])

# Group Tx
This section document Tx API resource

## Tx [/thorchain/tx/{hash}]

+ Parameters
    + hash: `E17A0906E015F0C343691C18E475C8CB5F3F6C63F5BCDE0F3A341909763CC92B` (required, string) - Tx hash of an inbound transaction or outbound transaction

+ Attributes
    + tx (ObservedTx) -  observed tx information
    + status (enum)
        + done
        + incomplete
    + out_hashes (array[string]) - a list of outbound hashes
    + block_height (string) - the block hight this tx get observed
    + signers (array[string]) - a list of signer address that has sign this tx off
    + observed_pub_key (string) - public key of the vault which observe this tx

### Get a tx with given hash [GET]
Retrieve a tx with the given hash from THORChain

+ Response 200 (application/json)
    + Body

            {
                "tx": {
                    "id": "CF524818D42B63D25BBA0CCC4909F127CAA645C0F9CD07324F2824CC151A64C7",
                    "chain": "BTC",
                    "from_address": "bcrt1q0s4mg25tu6termrk8egltfyme4q7sg3h8kkydt",
                    "to_address": "bcrt1qf3s7q037eancht7sg0aj995dht25rwrnqsf45e",
                    "coins": [
                    {
                        "asset": "BTC.BTC",
                        "amount": "150000000"
                    }],
                    "gas": [
                    {
                        "asset": "BTC.BTC",
                        "amount": "100000"
                    }],
                "memo": "ADD:BTC.BTC:tthor1zupk5lmc84r2dh738a9g3zscavannjy3nzplwt"
            },
            "status": "incomplete",
            "out_hashes": null,
            "block_height": "162",
            "signers": [
                "tthor1f3s7q037eancht7sg0aj995dht25rwrnu4ats5"
            ],
            "observed_pub_key": "tthorpub1addwnpepq27ck6u44zl8qqdnmzjjc8rg72amrxrsp42p9vd7kt6marhy6ww76z8shwe"
            }

## TxSigners [/thorchain/tx/{hash}/signers]

+ Parameters
    + hash: `E17A0906E015F0C343691C18E475C8CB5F3F6C63F5BCDE0F3A341909763CC92B` (required, string) - Tx hash of an inbound transaction or outbound transaction

+ Attributes
    + tx_id (string) - tx hash
    + tx (ObservedTx) - observed tx , the tx that reach 2/3 majority consensus
    + height (string) - block height that this tx reach super majority consensus
    + in_tx (array[ObservedTx]) - all observed tx
    + action - potential outbound tx
    + out_txs (array[string]) - outbound tx hashes

### Get tx signers [GET]
Get tx signers that match the request hash

+ Response 200 (application/json)
    + Body

            {
                "tx_id": "CF524818D42B63D25BBA0CCC4909F127CAA645C0F9CD07324F2824CC151A64C7",
                "tx": {
                    "tx": {
                    "id": "CF524818D42B63D25BBA0CCC4909F127CAA645C0F9CD07324F2824CC151A64C7",
                    "chain": "BTC",
                    "from_address": "bcrt1q0s4mg25tu6termrk8egltfyme4q7sg3h8kkydt",
                    "to_address": "bcrt1qf3s7q037eancht7sg0aj995dht25rwrnqsf45e",
                    "coins": [
                    {
                        "asset": "BTC.BTC",
                        "amount": "150000000"
                    }
                    ],
                    "gas": [
                    {
                        "asset": "BTC.BTC",
                        "amount": "100000"
                    }
                ],
                "memo": "ADD:BTC.BTC:tthor1zupk5lmc84r2dh738a9g3zscavannjy3nzplwt"
                },
                "status": "incomplete",
                "out_hashes": null,
                "block_height": "162",
                "signers": [
                    "tthor1f3s7q037eancht7sg0aj995dht25rwrnu4ats5"
                ],
                "observed_pub_key": "tthorpub1addwnpepq27ck6u44zl8qqdnmzjjc8rg72amrxrsp42p9vd7kt6marhy6ww76z8shwe"
                },
                "height": "15",
                "in_tx": [
                    {
                    "tx": {
                        "id": "CF524818D42B63D25BBA0CCC4909F127CAA645C0F9CD07324F2824CC151A64C7",
                        "chain": "BTC",
                        "from_address": "bcrt1q0s4mg25tu6termrk8egltfyme4q7sg3h8kkydt",
                        "to_address": "bcrt1qf3s7q037eancht7sg0aj995dht25rwrnqsf45e",
                        "coins": [
                        {
                            "asset": "BTC.BTC",
                            "amount": "150000000"
                        }
                        ],
                        "gas": [
                        {
                            "asset": "BTC.BTC",
                            "amount": "100000"
                        }
                        ],
                        "memo": "ADD:BTC.BTC:tthor1zupk5lmc84r2dh738a9g3zscavannjy3nzplwt"
                    },
                    "status": "incomplete",
                    "out_hashes": null,
                    "block_height": "162",
                    "signers": [
                        "tthor1f3s7q037eancht7sg0aj995dht25rwrnu4ats5"
                    ],
                    "observed_pub_key": "tthorpub1addwnpepq27ck6u44zl8qqdnmzjjc8rg72amrxrsp42p9vd7kt6marhy6ww76z8shwe"
                    }
                ],
                "actions": null,
                "out_txs": null
            }

# Group Nodes
This section document all the API for Node resource

## Node [/thorchain/node/{node_address}]

+ Parameters
    + node_address: `thor1f3s7q037eancht7sg0aj995dht25rwrnu4ats5` (string,required) - node address

+ Attributes
    + node_address (string) - node address
    + status (string) - status , values can be active,disabled,standby
    + pub_key_set
        + secp256k1 (string) - secp256k1 public key
        + ed25519 (string) - ed25519 public key
    + validator_cons_pub_key (string) - the consensus pubkey used by the node
    + bond (string) - current bond
    + active_block_height (string) - block height this node become active
    + bond_address (string) - bond address
    + status_since (string) - block height this node become current status
    + signer_membership (array[string]) - a list of vault public key that this node is a member of
    + requested_to_leave (boolean) - indicate whether this node had requested to leave_height
    + forced_to_leave (boolean) - indicate whether this node had been forced to leave by the network or not, if this field is true , usually means this node had been banned
    + ip_address (string) - node ip address
    + version (string) - the version of thornode software this node is running
    + slash_points (string) -  the slash points the node accumulated when they are active , slash points will be reset next time when node become active
    + jail
        + node_address (string) - node address
        + release_height (string) - on which block height , this node will be released from jail, if it is 0 , means the node is not in jail
        + reason (string) - why the node has been jailed
    + current_award (string) - node current award
    + observe_chains - chain and block heights this node is observing , this is useful to know whether a node is falling behind in regards to observing
    + preflight_status
        + status (string) - what status the node will be in next
        + reason (string) - why the node will be in the status above
        + code (string) - error code

### Get a node [GET]
Retrieve the node with given node address from THORChain

+ Response 200 (application/json)
    + Attributes (Node)
    + Body

            {
                "node_address": "tthor1257g60tcxvu4dvflpszgkwq34d5vw6pgz0wkdu",
                "status": "active",
                "pub_key_set": {
                    "secp256k1": "tthorpub1addwnpepqd9nqqmgay6mju0yq72ptjucmk9atawtev4v4n6wkee5y26q80eccg0xk37",
                    "ed25519": "tthorpub1zcjduepqcuwkyr4d0lfrftdla7f6nnkxuxu9p7grpfmy36jktv9wcqal5w3qgds2ch"
                },
                "validator_cons_pub_key": "tthorcpub1zcjduepq44vy0erpdcmekppgknu2u05znl8vmqs2nl0f92ezp4uj3zn695rqqdhta0",
                "bond": "0",
                "active_block_height": "1",
                "bond_address": "tbnb1ftdj7ttfa4chaf6xl04elnh30shhg4qvy4mw3r",
                "status_since": "0",
                "signer_membership": null,
                "requested_to_leave": false,
                "forced_to_leave": false,
                "leave_height": "0",
                "ip_address": "119.18.3.176",
                "version": "0.17.0",
                "slash_points": "1",
                "jail": {
                    "node_address": "tthor1257g60tcxvu4dvflpszgkwq34d5vw6pgz0wkdu",
                    "release_height": "0",
                    "reason": ""
                },
                "current_award": "0",
                "observe_chains": [
                    {
                        "chain": "BTC",
                        "height": "632"
                    },
                    {
                        "chain": "ETH",
                        "height": "6"
                    },
                    {
                        "chain": "BNB",
                        "height": "1883"
                    }
                ],
                "preflight_status": {
                    "status": "standby",
                    "reason": "node account does not have minimum bond requirement: 0/100000000",
                    "code": "1"
                }
            }


### Get all nodes [GET /thorchain/nodes]
Retrieve all nodes that have bond

+ Response 200 (application/json)
    + Attributes (array[Node])

# Group Vaults

## AsgardVault [/thorchain/vaults/asgard]

+ Attributes
    + block_height (string) - block height when the vault get created
    + pub_key (string) - vault's public key
    + coins (array[Coin]) - coins in this asgard vault
    + type (string) - vault type , it could be asgard or yggdrasil
    + status (string) - status , it could be active , retiring , inactive
    + status_since (string) - block height this vault get to current status
    + membership (array[string]) - a list of node public key , represent which nodes created this vault
    + chains (array[string]) - a list of chains this vault support
    + inbound_tx_count (string) - number of inbound tx to this vault , across all chain
    + outbound_tx_count (string) - number of outbound tx from this vault
    + pending_tx_heights (array[string]) - pending txes for migration
    + routers (array[ChainRouter]) - chain router
    + addresses (array[ChainAddress]) - chain addresses

### Get Asgard vaults [GET]
Retrieve all current active Asgard vaults from thorchain

+ Response 200 (application/json)
    + Attributes (array[AsgardVault])
    + Body

            [
                {
                    "block_height": 30,
                    "pub_key": "tthorpub1addwnpepqfha5sms6cyxgmr9y6j3lg5pxzyc3x9g4hkanlwu2j5jgkva4ncaurn5zmd",
                    "coins": [
                        {
                            "asset": "BNB.RUNE-67C",
                            "amount": "3000000000000000"
                        },
                        {
                            "asset": "BNB.BNB",
                            "amount": "100000000000"
                        },
                        {
                            "asset": "BNB.LOK-3C0",
                            "amount": "40000000000"
                        },
                        {
                            "asset": "BNB.BTCB-101",
                            "amount": "40000000000"
                        },
                        {
                            "asset": "BTC.BTC",
                            "amount": "100000000"
                        },
                        {
                            "asset": "LTC.LTC",
                            "amount": "500000000"
                        },
                        {
                            "asset": "BCH.BCH",
                            "amount": "500000000"
                        },
                        {
                            "asset": "ETH.TKN-0X3B7FA4DD21C6F9BA3CA375217EAD7CAB9D6BF483",
                            "amount": "500000000"
                        },
                        {
                            "asset": "ETH.ETH",
                            "amount": "1000000000"
                        }
                    ],
                    "type": "AsgardVault",
                    "status": "ActiveVault",
                    "membership": [
                        "tthorpub1addwnpepqfha5sms6cyxgmr9y6j3lg5pxzyc3x9g4hkanlwu2j5jgkva4ncaurn5zmd"
                    ],
                    "chains": [
                        "THOR",
                        "BTC",
                        "LTC",
                        "BCH",
                        "BNB",
                        "ETH"
                    ],
                    "inbound_tx_count": 11,
                    "routers": [
                        {
                            "chain": "ETH",
                            "router": "0xE65e9d372F8cAcc7b6dfcd4af6507851Ed31bb44"
                        }
                    ],
                    "addresses": [
                        {
                            "chain": "THOR",
                            "address": "tthor1syneecwgwvn6zkv47k3cq65fuzrp24yzxyk279"
                        },
                        {
                            "chain": "BTC",
                            "address": "bcrt1qsyneecwgwvn6zkv47k3cq65fuzrp24yz6pz56g"
                        },
                        {
                            "chain": "LTC",
                            "address": "rltc1qsyneecwgwvn6zkv47k3cq65fuzrp24yzyvcadk"
                        },
                        {
                            "chain": "BCH",
                            "address": "qzqj088pepej0g2ejh668qr238sgv925sg4g5hp57p"
                        },
                        {
                            "chain": "BNB",
                            "address": "tbnb1syneecwgwvn6zkv47k3cq65fuzrp24yzg9gfnq"
                        },
                        {
                            "chain": "ETH",
                            "address": "0x61666aa597b4344f855d25b92385b5eb0c650074"
                        }
                    ]
                }
            ]

## YggdrasilVault [/thorchain/vaults/yggdrasil]

+ Attributes
    + block_height (string) - block height when the vault get created
    + pub_key (string) - vault's public key
    + coins (array[Coin]) - coins in this asgard vault
    + type (string) - vault type, it could be asgard or yggdrasil
    + status_since (string) - block height this vault get to current status
    + membership (array[string]) - a list of node public key, represent which nodes created this vault
    + chains (array[string]) - a list of chains this vault support
    + inbound_tx_count (string) - number of inbound tx to this vault, across all chain
    + outbound_tx_count (string) - number of outbound tx from this vault
    + pending_tx_heights (array[string]) - pending txes for migration
    + routers (array[ChainRouter]) - chain router
    + status (string) - node status, it could be active, standby etc
    + bond (string) - bond
    + total_value (string) - total value in this yggdrasil vault
    + addresses (array[ChainAddress]) - chain addresses

### Get Yggdrasil vaults [GET /thorchain/vaults/yggdrasil]
Retrieve all Yggdrasil vaults from THORChain

+ Response 200 (application/json)
    + Attributes (array[YggdrasilVault])
    + Body

            [
                {
                    "block_height": "0",
                    "pub_key": "tthorpub1addwnpepqd9nqqmgay6mju0yq72ptjucmk9atawtev4v4n6wkee5y26q80eccg0xk37",
                    "coins": [
                    {
                        "asset": "BNB.BNB",
                        "amount": "0"
                    },
                    {
                        "asset": "BTC.BTC",
                        "amount": "0"
                    },
                    {
                        "asset": "ETH.ETH",
                        "amount": "3604472318"
                    },
                    {
                        "asset": "BNB.LOK-3C0",
                        "amount": "0"
                    },
                    {
                        "asset": "BNB.TCAN-014",
                        "amount": "1000000"
                    }
                    ],
                    "type": "yggdrasil",
                    "status": "active",
                    "status_since": "0",
                    "membership": [
                    "tthorpub1addwnpepqd9nqqmgay6mju0yq72ptjucmk9atawtev4v4n6wkee5y26q80eccg0xk37"
                    ],
                    "chains": [
                    "THOR",
                    "BTC",
                    "BNB",
                    "ETH"
                    ],
                    "inbound_tx_count": "21",
                    "outbound_tx_count": "23",
                    "pending_tx_heights": null,
                    "routers": [
                        {
                            "chain": "ETH",
                            "router": "0xE65e9d372F8cAcc7b6dfcd4af6507851Ed31bb44"
                        }
                    ],
                    "addresses": [
                        {
                            "chain": "THOR",
                            "address": "tthor1syneecwgwvn6zkv47k3cq65fuzrp24yzxyk279"
                        },
                        {
                            "chain": "BTC",
                            "address": "bcrt1qsyneecwgwvn6zkv47k3cq65fuzrp24yz6pz56g"
                        },
                        {
                            "chain": "LTC",
                            "address": "rltc1qsyneecwgwvn6zkv47k3cq65fuzrp24yzyvcadk"
                        },
                        {
                            "chain": "BCH",
                            "address": "qzqj088pepej0g2ejh668qr238sgv925sg4g5hp57p"
                        },
                        {
                            "chain": "BNB",
                            "address": "tbnb1syneecwgwvn6zkv47k3cq65fuzrp24yzg9gfnq"
                        },
                        {
                            "chain": "ETH",
                            "address": "0x61666aa597b4344f855d25b92385b5eb0c650074"
                        }
                    ]
                }
            ]

### Get a vault by pubkey [GET /thorchain/vault/{pubkey}]

+ Parameters
    + pubkey (string,required) - pubkey of the vault

+ Response 200 (application/json)
    + Attributes (AsgardVault)
    + Body

            {
                "block_height": 30,
                "pub_key": "tthorpub1addwnpepqfha5sms6cyxgmr9y6j3lg5pxzyc3x9g4hkanlwu2j5jgkva4ncaurn5zmd",
                "coins": [
                    {
                        "asset": "BNB.RUNE-67C",
                        "amount": "3000000000000000"
                    },
                    {
                        "asset": "BNB.BNB",
                        "amount": "100000000000"
                    },
                    {
                        "asset": "BNB.LOK-3C0",
                        "amount": "40000000000"
                    },
                    {
                        "asset": "BNB.BTCB-101",
                        "amount": "40000000000"
                    },
                    {
                        "asset": "BTC.BTC",
                        "amount": "100000000"
                    },
                    {
                        "asset": "LTC.LTC",
                        "amount": "500000000"
                    },
                    {
                        "asset": "BCH.BCH",
                        "amount": "500000000"
                    },
                    {
                        "asset": "ETH.TKN-0X3B7FA4DD21C6F9BA3CA375217EAD7CAB9D6BF483",
                        "amount": "500000000"
                    },
                    {
                        "asset": "ETH.ETH",
                        "amount": "1000000000"
                    }
                ],
                "type": "AsgardVault",
                "status": "ActiveVault",
                "membership": [
                    "tthorpub1addwnpepqfha5sms6cyxgmr9y6j3lg5pxzyc3x9g4hkanlwu2j5jgkva4ncaurn5zmd"
                ],
                "chains": [
                    "THOR",
                    "BTC",
                    "LTC",
                    "BCH",
                    "BNB",
                    "ETH"
                ],
                "inbound_tx_count": 11,
                "routers": [
                    {
                        "chain": "ETH",
                        "router": "0xE65e9d372F8cAcc7b6dfcd4af6507851Ed31bb44"
                    }
                ],
                "addresses": [
                    {
                        "chain": "THOR",
                        "address": "tthor1syneecwgwvn6zkv47k3cq65fuzrp24yzxyk279"
                    },
                    {
                        "chain": "BTC",
                        "address": "bcrt1qsyneecwgwvn6zkv47k3cq65fuzrp24yz6pz56g"
                    },
                    {
                        "chain": "LTC",
                        "address": "rltc1qsyneecwgwvn6zkv47k3cq65fuzrp24yzyvcadk"
                    },
                    {
                        "chain": "BCH",
                        "address": "qzqj088pepej0g2ejh668qr238sgv925sg4g5hp57p"
                    },
                    {
                        "chain": "BNB",
                        "address": "tbnb1syneecwgwvn6zkv47k3cq65fuzrp24yzg9gfnq"
                    },
                    {
                        "chain": "ETH",
                        "address": "0x61666aa597b4344f855d25b92385b5eb0c650074"
                    }
                ]
            }

### Get vault pubkeys [GET /thorchain/vaults/pubkeys]
Retrieve all vaults public keys

+ Response 200 (application/json)
    + Attributes
        + asgard (array[string]) - all Asgard vaults public key
        + yggdrasil (array[string]) - all Yggdrasil vaults publikc keys
    + Body

            {
                "asgard": [
                    "tthorpub1addwnpepqd9nqqmgay6mju0yq72ptjucmk9atawtev4v4n6wkee5y26q80eccg0xk37"
                ],
                "yggdrasil": []
            }

# Group Network
This section document all API related to THORChain network

## Network [/thorchain/network]

+ Attributes
    + bond_reward_rune (string) - total amount of awarded rune for node operators
    + total_bond_units (string) - total amount of bond units
    + total_reserve (string) - total amount of reserve in rune
    + burned_bep_2_rune (string) - total amount of burned BEP2 rune to native rune
    + burned_erc_20_rune (string) - total amount of burned ERC20 rune to native rune

### Get network data [GET]

Retrieve network data from THORChain

+ Response 200 (applicaton/json)
    + Attributes (Network)
    + Body

            {
                "bond_reward_rune": "857134475040",
                "total_bond_units": "0",
                "total_reserve": "21999180112172346",
                "burned_bep_2_rune": "674699077345087",
                "burned_erc_20_rune": "66369401654835"
            }

## InboundAddresses [/thorchain/inbound_addresses]
Inbound addresses will return a list of addresses, one per chain. The address might change frequently if THORChain has multiple Asgards.

+ Attributes
    + chain (string) - chain
    + pub_key (string) - public key
    + address (string) - address
    + halted (boolean) - indicate whether this chain has halted
    + gas_rate (string) - gas rate, for ETH, it is in Gwei, for BTC/BCH/LTC it is gas_rate per vbyte

### Get inbound addresses [GET]
Retrieve all the inbound addresses from THORChain

+ Response 200 (application/json)
    + Attributes (array[InboundAddresses])
    + Body

                [
                  {
                    "chain": "BCH",
                    "pub_key": "thorpub1addwnpepq2jqhv5rdqlkusfxy05stfzcgslhhz5qh8pxetw5ry2aa6awgdh3shq8s82",
                    "address": "qzvhxqm3clrhewqllfmt2ekuaa7puhwpns3kl5nj7a",
                    "gas_rate": "6"
                  },
                  {
                    "chain": "BNB",
                    "pub_key": "thorpub1addwnpepq2jqhv5rdqlkusfxy05stfzcgslhhz5qh8pxetw5ry2aa6awgdh3shq8s82",
                    "address": "bnb1n9esxuw8ca7ts8l6w66kdh800s09msvul6vlse",
                    "halted": true,
                    "gas_rate": "11250"
                  },
                  {
                    "chain": "BTC",
                    "pub_key": "thorpub1addwnpepq2jqhv5rdqlkusfxy05stfzcgslhhz5qh8pxetw5ry2aa6awgdh3shq8s82",
                    "address": "bc1qn9esxuw8ca7ts8l6w66kdh800s09msvutydc46",
                    "gas_rate": "214"
                  },
                  {
                    "chain": "ETH",
                    "pub_key": "thorpub1addwnpepq2jqhv5rdqlkusfxy05stfzcgslhhz5qh8pxetw5ry2aa6awgdh3shq8s82",
                    "address": "0x1091c4de6a3cf09cda00abdaed42c7c3b69c83ec",
                    "router": "0x42A5Ed456650a09Dc10EBc6361A7480fDd61f27B",
                    "gas_rate": "40"
                  },
                  {
                    "chain": "LTC",
                    "pub_key": "thorpub1addwnpepq2jqhv5rdqlkusfxy05stfzcgslhhz5qh8pxetw5ry2aa6awgdh3shq8s82",
                    "address": "ltc1qn9esxuw8ca7ts8l6w66kdh800s09msvu0chud2",
                    "gas_rate": "147"
                  }
                ]

## LastBlockHeight [/thorchain/lastblock/{chain}]
Last block height per chain

+ Parameters
    + chain: `BNB` (string,required) - chain

+ Attributes
    + chain (string) - chain
    + last_observed_in (number) - last observed in block height
    + last_sign_out (number) - last sign out block height
    + thorchain (number) - current thorchain block height

### Get last block height per chain [GET]
Retrieve the last block height information about the request chain

+ Response 200 (application/json)
    + Attributes (array[LastBlockHeight])
    + Body

            [
              {
                "chain": "BNB",
                "last_observed_in": 159097122,
                "last_signed_out": 233726,
                "thorchain": 233735
              }
            ]

### Get all last block height [GET /thorchain/lastblock]
Retrieve lastest block infomation across all chains

+ Response 200 (application/json)
    + Attributes (array[LastBlockHeight])
    + Body

        [
          {
            "chain": "BCH",
            "last_observed_in": 684829,
            "last_signed_out": 233674,
            "thorchain": 233727
          },
          {
            "chain": "BNB",
            "last_observed_in": 159097122,
            "last_signed_out": 233674,
            "thorchain": 233727
          },
          {
            "chain": "BTC",
            "last_observed_in": 680532,
            "last_signed_out": 233674,
            "thorchain": 233727
          },
          {
            "chain": "ETH",
            "last_observed_in": 12308554,
            "last_signed_out": 233674,
            "thorchain": 233727
          },
          {
            "chain": "LTC",
            "last_observed_in": 2040853,
            "last_signed_out": 233674,
            "thorchain": 233727
          }
        ]

## Version [/thorchain/version]
Network version using semantic version

+ Attributes
    + current (string) - current version
    + next (string) - next version

### Get current network version [GET]
Retrieve current network version from THORChain

+ Response 200 (application/json)
    + Attributes (Version)
    + Body

            {
                "current": "0.17.0",
                "next": "0.17.0"
            }

## Constants [/thorchain/constants]
Constant values used by THORChain, some of the values can be overrided by mimir

### Get constant values from THORChain [GET]
Retrieve constant values from THORChain

+ Response 200 (application/json)
    + Body

            {
              "int_64_values": {
                "AsgardSize": 40,
                "BadValidatorRate": 43200,
                "BadValidatorRedline": 3,
                "BlocksPerYear": 5256000,
                "ChurnInterval": 43200,
                "ChurnRetryInterval": 720,
                "DesiredValidatorSet": 100,
                "DoubleSignMaxAge": 24,
                "EmissionCurve": 6,
                "FailKeygenSlashPoints": 720,
                "FailKeysignSlashPoints": 2,
                "FullImpLossProtectionBlocks": 1440000,
                "FundMigrationInterval": 360,
                "IncentiveCurve": 100,
                "JailTimeKeygen": 4320,
                "JailTimeKeysign": 60,
                "LackOfObservationPenalty": 2,
                "LiquidityLockUpBlocks": 0,
                "MaxAvailablePools": 100,
                "MaxSwapsPerBlock": 100,
                "MinRunePoolDepth": 1000000000000,
                "MinSlashPointsForBadValidator": 100,
                "MinSwapsPerBlock": 10,
                "MinimumBondInRune": 100000000000000,
                "MinimumNodesForBFT": 4,
                "MinimumNodesForYggdrasil": 6,
                "NativeTransactionFee": 2000000,
                "ObservationDelayFlexibility": 10,
                "ObserveSlashPoints": 1,
                "OldValidatorRate": 43200,
                "OutboundTransactionFee": 2000000,
                "PoolCycle": 43200,
                "SigningTransactionPeriod": 300,
                "StagedPoolCost": 1000000000,
                "VirtualMultSynths": 2,
                "YggFundLimit": 50,
                "YggFundRetry": 1000
              },
              "bool_values": {
                "StrictBondLiquidityRatio": true
              },
              "string_values": {
                "DefaultPoolStatus": "Staged"
              }
            }

## Ragnarok [/thorchain/ragnarok]
This is just a true/false indicate whether THORChain is in Ragnarok or not

### Get Ragnarok status [GET]
+ Response 200 (application/json)
    + Attributes (boolean)
    + Body

            false

# Group Queue

## OutboundQueue [/thorchain/queue]

+ Attributes
    + swap (number) - number of swaps in the queue
    + outbound (number) - number of outbound tx in the queue for customer
    + internal (number) - number of internal tx in the queue. internal tx include migration,yggdrasil+

### Get outbound queue [GET]
Retrieve the outbound queue information from THORChain

+ Response 200 (application/json)
    + Attributes (OutboundQueue)
    + Body

            {
                "swap": 0,
                "outbound": 0,
                "internal": 0,
                "scheduled_outbound_value": "0"
            }

### Get scheduled outbound queue details [GET /thorchain/queue/scheduled]
Get the list of scheduled tx out items in the queue

+ Response 200 (application/json)
    + Attributes (array[TxOutItem])
    + Body

            [
                {
                    "chain": "TERRA",
                    "to_address": "terra1ljvh535tjk95hscf66yqx2gnzrczlmzehmvt27",
                    "vault_pub_key": "thorpub1addwnpepq2a8acdlryjfex4c32np3j2xynhqugr73ecwnrdkr4lphl0gfj5nc2h6c7g",
                    "coin": {
                        "asset": "TERRA.UST",
                        "amount": "1801677465300"
                    },
                    "memo": "OUT:2D730FA2A3643039A28EF66E86CB9A9C9AAD0C7EF584E653231C3477553DA3A6",
                    "max_gas": [
                        {
                            "asset": "TERRA.LUNA",
                            "amount": "380100",
                            "decimals": 6
                        }
                    ],
                    "gas_rate": 364900,
                    "in_hash": "2D730FA2A3643039A28EF66E86CB9A9C9AAD0C7EF584E653231C3477553DA3A6",
                    "height": 5412084
                }
            ]

### Get outbound queue details [GET /thorchain/queue/outbound]
Get the list of tx out items in the queue

+ Response 200 (application/json)
    + Attributes (array[TxOutItem])
    + Body

            [
                {
                    "chain": "TERRA",
                    "to_address": "terra1ljvh535tjk95hscf66yqx2gnzrczlmzehmvt27",
                    "vault_pub_key": "thorpub1addwnpepq2a8acdlryjfex4c32np3j2xynhqugr73ecwnrdkr4lphl0gfj5nc2h6c7g",
                    "coin": {
                        "asset": "TERRA.UST",
                        "amount": "1801677465300"
                    },
                    "memo": "OUT:2D730FA2A3643039A28EF66E86CB9A9C9AAD0C7EF584E653231C3477553DA3A6",
                    "max_gas": [
                        {
                            "asset": "TERRA.LUNA",
                            "amount": "380100",
                            "decimals": 6
                        }
                    ],
                    "gas_rate": 364900,
                    "in_hash": "2D730FA2A3643039A28EF66E86CB9A9C9AAD0C7EF584E653231C3477553DA3A6"
                }
            ]

# Group Keygen / Keysign

## Keygen [/thorchain/keygen/{height}/{pubkey}]

+ Parameters
    + height: 1024 (int,required) - block height
    + pubkey (string,required) - node public key

+ Attributes
    + keygen_block
        + height (string) - block height
        + keygens (array[string]) - a list node public keys , indicate who should be part of this keygen
    + signature (string) - base64 encoded signaure of the keygen block

### Get Keygen [GET]
Retrieve Keygen block from THORChain

+ Response 200 (application/json)
    + Attributes (Keygen)
    + Body

            {
                "keygen_block": {
                    "height": "1024",
                    "keygens": null
                },
                "signature": "NhKsZqRHNIMZ1Dw45/KQqFVcNBkl9B9/2MQrs5EinO4R5XlPSryW6SvRMe1f3//NLJ6yExqjmSBObR5+CClsqw=="
            }

## Keysign [/thorchain/keysign/{height}/{pubkey}]

+ Parameters
    + height: 1024 (int,required) - block height
    + pubkey (string,required) - node public key

+ Attributes
    + keysign
        + height (string) - block height, being the block(/s) in which a tx out item is scheduled to be signed and moved from the scheduled outbound queue to the outbound queue
        + tx_array (array[TxOutItem]) - list of tx out items
    + signature (string) - base64 encoded signature of keysign

### Get Keysign [GET]
Retrieve Keysign information from THORChain

+ Response 200 (application/json)
    + Attributes (Keysign)
    + Body

            {
                "keysign": {
                    "height": "18",
                    "tx_array": [
                    {
                        "chain": "BNB",
                        "to": "tbnb189az9plcke2c00vns0zfmllfpfdw67dtv25kgx",
                        "vault_pubkey": "tthorpub1addwnpepqd9nqqmgay6mju0yq72ptjucmk9atawtev4v4n6wkee5y26q80eccg0xk37",
                        "coin": {
                        "asset": "BNB.BNB",
                        "amount": "149887500"
                        },
                        "memo": "REFUND:50B303717A650F5D93B28CF34C8971E06382003AFFDB92E5935F3540D187490B",
                        "max_gas": [
                        {
                            "asset": "BNB.BNB",
                            "amount": "56250"
                        }
                        ],
                        "gas_rate": "56250",
                        "in_hash": "50B303717A650F5D93B28CF34C8971E06382003AFFDB92E5935F3540D187490B",
                        "out_hash": "601FB5AD52259BB023BC93996F40640CCC088B04528EB829E8FE9E9AC82F81C4"
                    }
                    ]
                },
                "signature": "0cJZ7kFoe6h3VA9yC/D+joTtfq7pJibxTK6GsjpHayNjapNCig20cqqSUerscKTwRPxB2D9DJaYVJ1C41wM9Bw=="
            }

# Group THORNames

## THORName [/thorchain/thorname/{name}]

+ Parameters
    + name (string,required) - THORName name

### Get Keygen [GET]
Retrieve THORName from THORChain

+ Response 200 (application/json)
    + Attributes (array[THORName])
    + Body

            [
                {
                    "name": "my-thorname",
                    "chain": "THOR",
                    "address": "thor1xxxxx",
                    "expire_block_height": 4000
                }
            ]


# Data Structures

## LiquidityProvider (object)
+ asset (string) -  the asset of the non-rune asset
+ rune_address (string) - the rune address of the liquidity provider
+ asset_address (string) - the non-rune asset address of the liquidity provider
+ last_add (string) - block height of the last add
+ last_withdraw (string) - block height of the last withdraw
+ units (string) - the total number of units of the pool
+ pending_rune (string) - rune that has been provided, but not committed yet. Awaiting a provision of the non-rune asset
+ pending_asset (string) - asset
+ pending_tx_id (string) - pending tx id

## Coin (object)
+ asset (string) - asset
+ amount (string) = amount

## ObservedTx (object)
+ id (string) - transaction hash
+ chain (string) - chain
+ from_address (string) - from address
+ to_address (string) - to address
+ coins (array[Coin]) - coins
+ gas  (array[Coin]) - amount of gas paid by the tx
+ memo (string) - memo

## TxOutItem (object)
+ chain (string) - chain
+ to (string) - to address
+ vault_pubkey (string) - vault public key
+ coin (Coin) - coin
+ memo (string) - memo
+ max_gas (Coin) - maxmum gas allowed to spend
+ gas_rate (string) - gas rate , signer has to use this gas rate to sign an outbound tx
+ in_hash (string) - inbound tx hash
+ out_hash (string) - outbound tx hash , this will be available after the txout item had been signed and observed back by bifrost

## ChainRouter (object)
+ chain (string) - chain
+ router (string) - router address

## ChainAddress (object)
+ chain (string) - chain
+ address (string) - address
